----------------------------------------------------------------------------
河海风云 (MudOS v22pre11) starting up on Microsoft Windows 95 - Sun Mar 05 21:52:17 2017


Can't find "mudos", ignoring old binaries.
Try invoking the driver using the full pathname.
System Error: init_addr_server: connect:由于目标计算机积极拒绝，无法连接。


Loading preloaded files ...
Initializations complete.

Accepting connections on port 5555.

执行时段错误：*F_SKILL: No such skill (tianyu-qijian)

程式：feature/skill.c 第 18 行
物件: /d/lingjiu/npc/yupopo
呼叫来自：feature/command.c 的 command_hook() 第 43 行，物件： obj/user#2 ("冷剑")
呼叫来自：cmds/std/go.c 的 main() 第 57 行，物件： cmds/std/go
呼叫来自：d/lingjiu/jian.c 的 create() 第 27 行，物件： d/lingjiu/jian
呼叫来自：std/room.c 的 setup() 第 203 行，物件： d/lingjiu/jian
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/jian
呼叫来自：std/room.c 的 make_inventory() 第 19 行，物件： d/lingjiu/jian
呼叫来自：d/lingjiu/npc/yupopo.c 的 create() 第 42 行，物件： d/lingjiu/npc/yupopo ("余婆婆")
呼叫来自：feature/skill.c 的 set_skill() 第 18 行，物件： d/lingjiu/npc/yupopo ("余婆婆")

执行时段错误：*Wrong permissions for opening file /log/static/gaoshou for append.
"No such file or directory"

程式：adm/obj/simul_efun.c 第 10 行
物件: /adm/obj/simul_efun
呼叫来自：adm/daemons/logind.c 的 get_passwd() 第 185 行，物件： adm/daemons/logind
呼叫来自：adm/daemons/logind.c 的 enter_world() 第 479 行，物件： adm/daemons/logind
呼叫来自：adm/daemons/gaoshoud.c 的 set_gaoshou() 第 129 行，物件： adm/daemons/gaoshoud
呼叫来自：adm/obj/simul_efun.c 的 log_file() 第 10 行，物件： adm/obj/simul_efun

执行时段错误：*F_SKILL: No such skill (tianyu-qijian)

程式：feature/skill.c 第 18 行
物件: /d/lingjiu/npc/yupopo#466
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/jian
呼叫来自：std/room.c 的 make_inventory() 第 19 行，物件： d/lingjiu/jian
呼叫来自：d/lingjiu/npc/yupopo.c 的 create() 第 42 行，物件： d/lingjiu/npc/yupopo#466 ("余婆婆")
呼叫来自：feature/skill.c 的 set_skill() 第 18 行，物件： d/lingjiu/npc/yupopo#466 ("余婆婆")
System Error: flush_message: write:无法立即完成一个非阻止性套接字操作。


执行时段错误：*F_SKILL: No such skill (tianyu-qijian)

程式：feature/skill.c 第 18 行
物件: /d/lingjiu/npc/yupopo#847
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/jian
呼叫来自：std/room.c 的 make_inventory() 第 19 行，物件： d/lingjiu/jian
呼叫来自：d/lingjiu/npc/yupopo.c 的 create() 第 42 行，物件： d/lingjiu/npc/yupopo#847 ("余婆婆")
呼叫来自：feature/skill.c 的 set_skill() 第 18 行，物件： d/lingjiu/npc/yupopo#847 ("余婆婆")

执行时段错误：*Error in loading object '/daemon/skill/dugu-jiujian/po'

程式：std/skill.c 第 97 行
物件: /daemon/skill/dugu-jiujian
呼叫来自：feature/command.c 的 command_hook() 第 43 行，物件： obj/user#877 ("冷剑")
呼叫来自：cmds/std/perform.c 的 main() 第 30 行，物件： cmds/std/perform
呼叫来自：std/skill.c 的 perform_action() 第 97 行，物件： daemon/skill/dugu-jiujian

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：adm/obj/simul_efun.c 第 8 行
物件: /adm/obj/simul_efun
呼叫来自：d/jingcheng/npc/youxia.c 的 greeting() 第 71 行，物件： d/jingcheng/npc/youxia#1157 ("游侠儿")
呼叫来自：adm/obj/simul_efun.c 的 message_vision() 第 8 行，物件： adm/obj/simul_efun

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：adm/obj/simul_efun.c 第 8 行
物件: /adm/obj/simul_efun
呼叫来自：d/jingcheng/npc/youxia.c 的 greeting() 第 76 行，物件： d/jingcheng/npc/youxia#1154 ("游侠儿")
呼叫来自：adm/obj/simul_efun.c 的 message_vision() 第 8 行，物件： adm/obj/simul_efun

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/damen
呼叫来自：feature/command.c 的 command_hook() 第 43 行，物件： obj/user#877 ("冷剑")
呼叫来自：cmds/std/go.c 的 main() 第 57 行，物件： cmds/std/go
呼叫来自：d/lingjiu/damen.c 的 create() 第 23 行，物件： d/lingjiu/damen
呼叫来自：std/room.c 的 setup() 第 203 行，物件： d/lingjiu/damen
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/damen
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/damen

执行时段错误：*call_other() couldn't find object

程式：d/lingjiu/dating.c 第 23 行
物件: /d/lingjiu/dating
呼叫来自：feature/command.c 的 command_hook() 第 43 行，物件： obj/user#877 ("冷剑")
呼叫来自：cmds/std/go.c 的 main() 第 57 行，物件： cmds/std/go
呼叫来自：d/lingjiu/dating.c 的 create() 第 23 行，物件： d/lingjiu/dating

执行时段错误：*F_DAMAGE: 伤害种类错误( 只能是 gin, kee, sen 其中之一 )。

程式：feature/damage.c 第 18 行
物件: /obj/user#877
呼叫来自：feature/command.c 的 command_hook() 第 43 行，物件： obj/user#877 ("冷剑")
呼叫来自：cmds/std/go.c 的 main() 第 77 行，物件： cmds/std/go
呼叫来自：feature/move.c 的 move() 第 82 行，物件： obj/user#877 ("冷剑")
呼叫来自：d/lingjiu/changl15.c 的 init() 第 36 行，物件： d/lingjiu/changl15
呼叫来自：feature/damage.c 的 receive_damage() 第 18 行，物件： obj/user#877 ("冷剑")

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：feature/command.c 的 command_hook() 第 43 行，物件： obj/user#877 ("冷剑")
呼叫来自：cmds/std/go.c 的 main() 第 57 行，物件： cmds/std/go
呼叫来自：d/lingjiu/xiaodao1.c 的 create() 第 21 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 setup() 第 203 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1
get_user_data: read on fd 584
System Error: get_user_data: read:当文件已存在时，无法创建该文件。


执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1
get_user_data: read on fd 588
System Error: get_user_data: read:当文件已存在时，无法创建该文件。


执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1
get_user_data: read on fd 588
System Error: get_user_data: read:当文件已存在时，无法创建该文件。


执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1

执行时段错误：*Bad argument 1 to call_other()
Expected: string or array or object Got: 0.

程式：std/room.c 第 20 行
物件: /d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 reset() 第 54 行，物件： d/lingjiu/xiaodao1
呼叫来自：std/room.c 的 make_inventory() 第 20 行，物件： d/lingjiu/xiaodao1
get_user_data: read on fd 588
System Error: get_user_data: read:当文件已存在时，无法创建该文件。

